# Generated by Django 5.2 on 2025-04-23 23:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_batch_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbatch',
            options={'ordering': ['purchase_date']},
        ),
        migrations.RemoveField(
            model_name='batchsaleitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='productbatch',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='batchsaleitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.productbatch'),
        ),
        migrations.AlterField(
            model_name='batchsaleitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='batchsaleitem',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.saleitem'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='batch_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.product'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='remaining_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
