# Generated by Django 5.1.7 on 2025-05-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_product_forecasts'),
        ('api', '0007_create_product_forecasts'),
    ]

    operations = [
    ]
