# Generated by Django 5.1.7 on 2025-05-15 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250515_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productforecast',
            options={'ordering': ['forecast_date']},
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
