# Generated by Django 5.1.7 on 2025-05-15 14:07

from django.db import migrations, models
import django.utils.timezone

def backfill_batches(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    ProductBatch = apps.get_model('api', 'ProductBatch')
    for product in Product.objects.all():
        if not ProductBatch.objects.filter(product_id=product.id).exists():
            ProductBatch.objects.create(
                product_id=product.id,
                batch_number=f"INIT-{product.id}",
                purchase_price=product.buy_price,
                selling_price=product.sell_price,
                quantity=product.quantity,
                remaining_quantity=product.quantity,
                purchase_date=product.created_at,
            )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_productforecast_options_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_batches, reverse_code=migrations.RunPython.noop),
    ]
