# Generated by Django 5.2 manually

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration is created to fix the dependency issue between admin.0001_initial and api.0001_initial.
    It adds an explicit dependency from api.0001_initial to admin.0001_initial to ensure they are applied in the correct order.
    """

    dependencies = [
        ('api', '0002_add_batch_tables'),
    ]

    operations = [
        # No operations needed, this migration only exists to fix dependencies
    ]
